USE [shares];

BEGIN TRANSACTION

CREATE TABLE [dbo].[trendlinesBreaks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TrendlineId] [int] NOT NULL,
	[DateIndex] [int] NOT NULL,
	[BreakFromAbove] [int] NOT NULL,
	CONSTRAINT [PK_trendlinesBreaks] PRIMARY KEY CLUSTERED ([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE NONCLUSTERED INDEX [ixId_trendlinesBreaks] ON [dbo].[trendlinesBreaks]
([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

CREATE NONCLUSTERED INDEX [ixTrendlineId_trendlinesBreaks] ON [dbo].[trendlinesBreaks]
([TrendlineId] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

CREATE NONCLUSTERED INDEX [ixDateIndex_trendlinesBreaks] ON [dbo].[trendlinesBreaks]
([DateIndex] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)


CREATE TABLE [dbo].[TrendlinesHits](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TrendlineId] [int] NOT NULL,
	[ExtremumGroupId] [int] NOT NULL,
	[DateIndex] [int] NOT NULL,
	CONSTRAINT [PK_trendlinesHits] PRIMARY KEY CLUSTERED ([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE NONCLUSTERED INDEX [ixId_trendlinesHits] ON [dbo].[TrendlinesHits]
([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

CREATE NONCLUSTERED INDEX [ixTrendlineId_trendlinesHits] ON [dbo].[TrendlinesHits]
([TrendlineId] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

CREATE NONCLUSTERED INDEX [ixDateIndex_trendlinesHits] ON [dbo].[TrendlinesHits]
([DateIndex] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)


CREATE TABLE [dbo].[TrendRanges](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TrendlineId] [int] NOT NULL,
	[BaseId] [int] NOT NULL,
	[BaseIsHit] [int] NOT NULL,
	[BaseDateIndex] [int] NOT NULL,
	[CounterId] [int] NOT NULL,
	[CounterIsHit] [int] NOT NULL,
	[CounterDateIndex] [int] NOT NULL,
	[IsPeak] [int] NOT NULL,
	[ExtremumPriceCrossPenaltyPoints] [float] NULL,
	[OCPriceCrossPenaltyPoints] [float] NULL,
	[TotalCandles] [int] NULL,
	[AverageVariation] [float] NULL,
	[ExtremumVariation] [float] NULL,
	[OpenCloseVariation] [float] NULL,
	[BaseHitValue] [float] NULL,
	[CounterHitValue] [float] NULL,
	[Value] [float] NULL,
	[ExtremumPriceCrossCounter] [int] NULL,
	[OCPriceCrossCounter] [int] NULL,
	CONSTRAINT [PK_trendRanges] PRIMARY KEY CLUSTERED ([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE NONCLUSTERED INDEX [ixId_trendRanges] ON [dbo].[TrendRanges]
([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

CREATE NONCLUSTERED INDEX [ixTrendlineId_trendRanges] ON [dbo].[TrendRanges]
([TrendlineId] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

CREATE NONCLUSTERED INDEX [ixBaseId_trendRanges] ON [dbo].[TrendRanges]
([BaseId] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

CREATE NONCLUSTERED INDEX [ixBaseDateIndex_trendRanges] ON [dbo].[TrendRanges]
([BaseDateIndex] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

CREATE NONCLUSTERED INDEX [ixCounterId_trendRanges] ON [dbo].[TrendRanges]
([CounterId] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

CREATE NONCLUSTERED INDEX [ixCounterDateIndex_trendRanges] ON [dbo].[TrendRanges]
([CounterDateIndex] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)


COMMIT TRANSACTION;